### ISSUE TITLE
Move to ubuntu from debian?

### ISSUE THREAD

**Issue by adampetrovic** [timhaak/docker-sickrage#1]
How would you feel about transitioning to ubuntu 14.04? For consistency with your Sickbeard repo?

I've tested in my fork and have it working fine.

**Comment by timhaak** [comment]
Actually won't really have a problem. Initially it was using Ubuntu. Though moved to debian as it created the smallest image size. (The debian base image is quiet a bit smaller).

Though use Ubuntu for most other things.

**Comment by timhaak** [comment]
Change has been merged
