### ISSUE TITLE
Unrar executable

### ISSUE THREAD

**Issue by pettenstein** [timhaak/docker-sickrage#3]
Would it be possible to add the Unrar executable? Right now the Unpack feature doesn't work.

> Unpack any TV releases in your TV Download Dir?
> NOTE: Only working with RAR archive

> **Unrar Executable not found.**

**Comment by haugene** [comment]
Just to make sure, have you pulled the image from docker registry recently? As this pull request addressed unrar and was merged two weeks ago... https://github.com/timhaak/docker-sickrage/pull/2

If so, do you have docker logs?

**Comment by pettenstein** [comment]
Yeah, I saw that. But in 882298941bd1571478517471e0a15592fb081f24 he took it out again.

**Comment by haugene** [comment]
So it's me who haven't got the newest one :) Anyways, he included it in his base image a few days ago.
https://github.com/timhaak/docker-base/commit/2de610e9766b15cbd44be07dccd37445896abb74

I just did the following:
docker pull timhaak/sickrage
docker run -it timhaak/sickrage bash

And then inside the sickrage image, unrar is avaliable. Can you check the same? Or se if "unrar" package exists inside your current image?

**Comment by timhaak** [comment]
It should be there. Its in the base image

https://github.com/timhaak/docker-base/blob/master/Dockerfile

**Comment by timhaak** [comment]
Ah sorry saw that you said that. Was fault on my side forgot to push the update to the base that added it.

I had made the change on my side to both at the same time.

Trying to make it slightly more manageable on my side and that if you pull two images there is more sharing.

**Comment by pettenstein** [comment]
I just rebuild and it seems to work.
Thanks for getting back to me!

**Comment by timhaak** [comment]
Pleasure :)
