### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by abibouba** [timhaak/docker-sickrage#4]
Hello Timhaak,
Many thanks for this easy to use image. I have one problem though. Sickrage is not able to fetch torr**** from some providers with ssl connection (like TPB, KAT …). Are you able to do it?
I think there is a problem with the openssl version included in the package. Please check this thread https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors

**Comment by timhaak** [comment]
Hmm.

I haven't had that problem this side. Though doesn't mean it doesn't exist.

I've added python-openssl to be installed in the image (It seems to install the required version).

I've pushed it and it should be building the new image as we speak.

If you could test to see if it resolves it your side please in about 1 hour from now. (just do a new pull).

If that doesn't work I'll follow the examples in the link where you use pip to do the build. Just trying to save some space in the image for now :)

**Comment by abibouba** [comment]
Great.  
Thanks for the quick feedback. I will let you know tonight when I do the test.

**Comment by abibouba** [comment]
Thanks again.
It did the trick.

**Comment by timhaak** [comment]
Awsome :).
