### ISSUE TITLE
Git update

### ISSUE THREAD

**Issue by R0GGER** [timhaak/docker-sickrage#5]
Hello Tim,

This image works great except when it tries to update (git).
It's trying to restart and the container stops, but won't restart automatically.

Rog

**Comment by R0GGER** [comment]
With supervisor you can solve this issue...

**Comment by timhaak** [comment]
Hi have you tried running it with --restart=always ?

I'm aware of the supervisor solution. Though with docker having added the restart option its a cleaner solution

**Comment by R0GGER** [comment]
Yes, I tried that... But doesn't work...

**Comment by timhaak** [comment]
Hi just did a test on my side with the restart=always and it worked fine.

Can you see what's happening on your side that this isn't working?
