### ISSUE TITLE
New SickRage

### ISSUE THREAD

**Issue by Rafkat** [timhaak/docker-sickrage#6]
Hi,
It seems that new SickRage has just evolved - https://github.com/SickRage/SickRage
Are you planning to switch your docker to that?

**Comment by timhaak** [comment]
After looking through what's going on and the history behind this fork.

The fork should call itself something new.

I have no problem with the split or with creating a docker image for the new version but not with the same name.

Once the fork has rebranded let me know I'll happily create a new Docker image and even see how it compares. 

Unfortunately I have no idea of the politics and am uninvolved with the project. 

Your message above is a bit deceitful "SickRage has just evolved".

As from what I gather it's more a disagreement with how things should be run and hence a fork. No evolution involved.

**Comment by Rafkat** [comment]
Yeh, that’s jut my english not good, perhaps. Feel free to close the ticket on github. 


Thanks
